services:
  openclaw-aio:
    container_name: opencode-aio
    image: fellow99/opencode-aio:1.3.13
    restart: unless-stopped
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - DAC_OVERRIDE
    env_file: .env
    volumes:
      - ./opencode-aio.pm2.json:/root/opencode-aio.pm2.json
      - ./.opencode/opencode.json:/root/.config/opencode/opencode.json
      - ./.opencode/oh-my-opencode.json:/root/.config/opencode/oh-my-opencode.json
      - ./.opencode/plugins/:/root/.config/opencode/plugins/
      - ./.local_share_opencode:/root/.local/share/opencode
      - ./.local_state_opencode:/root/.local/state/opencode
      - ./.agents:/root/.agents
      - ./.m2:/root/.m2
      - ./.gradle:/root/.gradle
      - ./workspace:/root/workspace
      - ./user-data:/root/user-data
    ports:
      - 4096:4096
      - 8931:8931
      - 6080:6080
      - 5173:5173
      - 8080:8080
      - 8000:8000
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
