ARG JAVA_MAJOR_VERSION=17

FROM fellow99/playwright-vnc:latest

ENV HOME=/root

RUN curl -s https://get.sdkman.io | bash && \
    chmod a+x "$HOME/.sdkman/bin/sdkman-init.sh" && \
    source "$HOME/.sdkman/bin/sdkman-init.sh" && \
    sdk install java 17-open && \
    sdk install maven && \
    sdk install gradle && \
    sdk default java 17-open && \
    sdk flush archives && \
    sdk flush temp

ENV SDKMAN_DIR=$HOME/.sdkman
ENV JAVA_HOME=$SDKMAN_DIR/candidates/java/current
ENV MAVEN_HOME=$SDKMAN_DIR/candidates/maven/current
ENV GRADLE_HOME=$SDKMAN_DIR/candidates/gradle/current

ENV PATH=$JAVA_HOME/bin:$MAVEN_HOME/bin:$GRADLE_HOME/bin:$PATH

COPY init-sdkman.sh $HOME/
RUN chmod 755 $HOME/init-sdkman.sh

COPY playwright-sdkman.pm2.json $HOME/playwright-sdkman.pm2.json

CMD ["sh", "-c", "pm2-runtime start $HOME/playwright-sdkman.pm2.json"]
