services:
  dev-opencode:
    image: fellow99/dev-opencode:1.14.25
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./opencode-aio.pm2.json:/root/opencode-aio.pm2.json
      - ./.opencode/opencode.json:/root/.config/opencode/opencode.json
      - ./.opencode/oh-my-openagent.json:/root/.config/opencode/oh-my-openagent.json
      - ./.opencode/plugins/:/root/.config/opencode/plugins/
      - ./.local_share_opencode:/root/.local/share/opencode
      - ./.local_state_opencode:/root/.local/state/opencode
      - ./.agents:/root/.agents
      - ./.m2:/root/.m2
      - ./.gradle:/root/.gradle
      - ./workspace:/root/workspace
    ports:
      - 2222:22
      - 4096:4096
      - 8931:8931
      - 6080:6080
      - 5173:5173
      - 8080:8080
      - 8000:8000
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
